name: 'Discord Webhook'
description: 'Notify about failed build via discord webhook'
inputs:
  discord-webhook:
    description: 'Webhook URL of discord server'
    required: true
    default: '-'
  branch:
    description: 'Branch the failure happend on'
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Discord Notification
      env:
        JOB_STATUS: ${{ job.status }}
        HOOK_OS_NAME: ${{ runner.os }}
        WORKFLOW_NAME: ${{ github.workflow }}
        BRANCH: ${{ inputs.branch }}
      run: ${{ github.action_path }}/run.sh ${{ inputs.discord-webhook }}
      shell: bash
